#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SampleProcessButton.Resource", IsApplication=true)]

namespace SampleProcessButton
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Library.Resource.Attribute.pb_colorComplete = global::SampleProcessButton.Resource.Attribute.pb_colorComplete;
			global::Library.Resource.Attribute.pb_colorError = global::SampleProcessButton.Resource.Attribute.pb_colorError;
			global::Library.Resource.Attribute.pb_colorNormal = global::SampleProcessButton.Resource.Attribute.pb_colorNormal;
			global::Library.Resource.Attribute.pb_colorPressed = global::SampleProcessButton.Resource.Attribute.pb_colorPressed;
			global::Library.Resource.Attribute.pb_colorProgress = global::SampleProcessButton.Resource.Attribute.pb_colorProgress;
			global::Library.Resource.Attribute.pb_cornerRadius = global::SampleProcessButton.Resource.Attribute.pb_cornerRadius;
			global::Library.Resource.Attribute.pb_textComplete = global::SampleProcessButton.Resource.Attribute.pb_textComplete;
			global::Library.Resource.Attribute.pb_textError = global::SampleProcessButton.Resource.Attribute.pb_textError;
			global::Library.Resource.Attribute.pb_textProgress = global::SampleProcessButton.Resource.Attribute.pb_textProgress;
			global::Library.Resource.Color.blue_normal = global::SampleProcessButton.Resource.Color.blue_normal;
			global::Library.Resource.Color.blue_pressed = global::SampleProcessButton.Resource.Color.blue_pressed;
			global::Library.Resource.Color.green_complete = global::SampleProcessButton.Resource.Color.green_complete;
			global::Library.Resource.Color.holo_blue_bright = global::SampleProcessButton.Resource.Color.holo_blue_bright;
			global::Library.Resource.Color.holo_green_light = global::SampleProcessButton.Resource.Color.holo_green_light;
			global::Library.Resource.Color.holo_orange_light = global::SampleProcessButton.Resource.Color.holo_orange_light;
			global::Library.Resource.Color.holo_red_light = global::SampleProcessButton.Resource.Color.holo_red_light;
			global::Library.Resource.Color.purple_progress = global::SampleProcessButton.Resource.Color.purple_progress;
			global::Library.Resource.Color.red_error = global::SampleProcessButton.Resource.Color.red_error;
			global::Library.Resource.Dimension.corner_radius = global::SampleProcessButton.Resource.Dimension.corner_radius;
			global::Library.Resource.Dimension.layer_padding = global::SampleProcessButton.Resource.Dimension.layer_padding;
			global::Library.Resource.Drawable.rect_complete = global::SampleProcessButton.Resource.Drawable.rect_complete;
			global::Library.Resource.Drawable.rect_error = global::SampleProcessButton.Resource.Drawable.rect_error;
			global::Library.Resource.Drawable.rect_normal = global::SampleProcessButton.Resource.Drawable.rect_normal;
			global::Library.Resource.Drawable.rect_pressed = global::SampleProcessButton.Resource.Drawable.rect_pressed;
			global::Library.Resource.Drawable.rect_progress = global::SampleProcessButton.Resource.Drawable.rect_progress;
			global::Library.Resource.String.define_processbutton = global::SampleProcessButton.Resource.String.define_processbutton;
			global::Library.Resource.String.library_name = global::SampleProcessButton.Resource.String.library_name;
			global::Library.Resource.String.library_processbutton_author = global::SampleProcessButton.Resource.String.library_processbutton_author;
			global::Library.Resource.String.library_processbutton_authorWebsite = global::SampleProcessButton.Resource.String.library_processbutton_authorWebsite;
			global::Library.Resource.String.library_processbutton_isOpenSource = global::SampleProcessButton.Resource.String.library_processbutton_isOpenSource;
			global::Library.Resource.String.library_processbutton_libraryDescription = global::SampleProcessButton.Resource.String.library_processbutton_libraryDescription;
			global::Library.Resource.String.library_processbutton_libraryName = global::SampleProcessButton.Resource.String.library_processbutton_libraryName;
			global::Library.Resource.String.library_processbutton_libraryVersion = global::SampleProcessButton.Resource.String.library_processbutton_libraryVersion;
			global::Library.Resource.String.library_processbutton_libraryWebsite = global::SampleProcessButton.Resource.String.library_processbutton_libraryWebsite;
			global::Library.Resource.String.library_processbutton_licenseId = global::SampleProcessButton.Resource.String.library_processbutton_licenseId;
			global::Library.Resource.String.library_processbutton_repositoryLink = global::SampleProcessButton.Resource.String.library_processbutton_repositoryLink;
			global::Library.Resource.Styleable.FlatButton = global::SampleProcessButton.Resource.Styleable.FlatButton;
			global::Library.Resource.Styleable.FlatButton_pb_colorNormal = global::SampleProcessButton.Resource.Styleable.FlatButton_pb_colorNormal;
			global::Library.Resource.Styleable.FlatButton_pb_colorPressed = global::SampleProcessButton.Resource.Styleable.FlatButton_pb_colorPressed;
			global::Library.Resource.Styleable.FlatButton_pb_cornerRadius = global::SampleProcessButton.Resource.Styleable.FlatButton_pb_cornerRadius;
			global::Library.Resource.Styleable.ProcessButton = global::SampleProcessButton.Resource.Styleable.ProcessButton;
			global::Library.Resource.Styleable.ProcessButton_pb_colorComplete = global::SampleProcessButton.Resource.Styleable.ProcessButton_pb_colorComplete;
			global::Library.Resource.Styleable.ProcessButton_pb_colorError = global::SampleProcessButton.Resource.Styleable.ProcessButton_pb_colorError;
			global::Library.Resource.Styleable.ProcessButton_pb_colorProgress = global::SampleProcessButton.Resource.Styleable.ProcessButton_pb_colorProgress;
			global::Library.Resource.Styleable.ProcessButton_pb_textComplete = global::SampleProcessButton.Resource.Styleable.ProcessButton_pb_textComplete;
			global::Library.Resource.Styleable.ProcessButton_pb_textError = global::SampleProcessButton.Resource.Styleable.ProcessButton_pb_textError;
			global::Library.Resource.Styleable.ProcessButton_pb_textProgress = global::SampleProcessButton.Resource.Styleable.ProcessButton_pb_textProgress;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int sample_list = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int pb_colorComplete = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int pb_colorError = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int pb_colorNormal = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int pb_colorPressed = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int pb_colorProgress = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int pb_cornerRadius = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int pb_textComplete = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int pb_textError = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int pb_textProgress = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int blue_normal = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int blue_pressed = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int green_complete = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int holo_blue_bright = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int holo_green_light = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int holo_orange_light = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int holo_red_light = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int purple_progress = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int red_error = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int corner_radius = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int layer_padding = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int rect_complete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int rect_error = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rect_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int rect_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int rect_progress = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int btnAction = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int btnGenerate = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int btnProgressComplete = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int btnProgressError = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int btnProgressLoading = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int btnProgressNormal = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int btnSend = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int btnSignIn = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int btnSubmit = 2131230726;
			
			// aapt resource value: 0x7f08000c
			public const int btnUpload = 2131230732;
			
			// aapt resource value: 0x7f080002
			public const int editEmail = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int editMessage = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int editPassword = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ac_message = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ac_sign_in = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ac_states = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ac_upload = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060016
			public const int Beautiful_Picture = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int Done = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int Loading = 2131099665;
			
			// aapt resource value: 0x7f060018
			public const int Loading_Complete = 2131099672;
			
			// aapt resource value: 0x7f060012
			public const int Question = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int Send = 2131099667;
			
			// aapt resource value: 0x7f06000f
			public const int Sign_in = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int Success = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int Upload = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int Uploading = 2131099671;
			
			// aapt resource value: 0x7f06000c
			public const int action_settings = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int app_name = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int define_processbutton = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int dummy_email = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int dummy_password = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int library_processbutton_author = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int library_processbutton_authorWebsite = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int library_processbutton_isOpenSource = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int library_processbutton_libraryDescription = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int library_processbutton_libraryName = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int library_processbutton_libraryVersion = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int library_processbutton_libraryWebsite = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int library_processbutton_licenseId = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int library_processbutton_repositoryLink = 2131099658;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlatButton = new int[]
			{
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int FlatButton_pb_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FlatButton_pb_colorPressed = 0;
			
			// aapt resource value: 2
			public const int FlatButton_pb_cornerRadius = 2;
			
			public static int[] ProcessButton = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 4
			public const int ProcessButton_pb_colorComplete = 4;
			
			// aapt resource value: 5
			public const int ProcessButton_pb_colorError = 5;
			
			// aapt resource value: 3
			public const int ProcessButton_pb_colorProgress = 3;
			
			// aapt resource value: 1
			public const int ProcessButton_pb_textComplete = 1;
			
			// aapt resource value: 2
			public const int ProcessButton_pb_textError = 2;
			
			// aapt resource value: 0
			public const int ProcessButton_pb_textProgress = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
