#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SlidingMenuSharp.Resource", IsApplication=false)]

namespace SlidingMenuSharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public static int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public static int fadeDegree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public static int fadeEnabled = 2130771978;
			
			// aapt resource value: 0x7f010000
			public static int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public static int selectorDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public static int selectorEnabled = 2130771980;
			
			// aapt resource value: 0x7f010008
			public static int shadowDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int shadowWidth = 2130771977;
			
			// aapt resource value: 0x7f010006
			public static int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int touchModeBehind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public static int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int viewBehind = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030003
			public static int fullscreen = 2130903043;
			
			// aapt resource value: 0x7f030000
			public static int left = 2130903040;
			
			// aapt resource value: 0x7f030002
			public static int margin = 2130903042;
			
			// aapt resource value: 0x7f030001
			public static int right = 2130903041;
			
			// aapt resource value: 0x7f030004
			public static int selected_view = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int slidingmenumain = 2130903045;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int slidingmenumain = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SlidingMenu = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public static int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public static int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public static int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public static int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public static int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public static int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public static int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public static int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public static int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public static int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public static int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public static int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public static int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public static int SlidingMenu_viewBehind = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
