#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AnimationDrawer.Resource", IsApplication=true)]

namespace AnimationDrawer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int allowSingleTap = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int animateOnClick = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int bottomOffset = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int content = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int direction = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int handle = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int topOffset = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawer_pattern = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pattern1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sliding_drawer_handle_bottom = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000b
			public const int bar_alpha = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int bar_blur = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int bar_size = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int bottomToTop = 2130968577;
			
			// aapt resource value: 0x7f04000f
			public const int button_close = 2130968591;
			
			// aapt resource value: 0x7f040004
			public const int button_open = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int content = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int drawer = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int handle = 2130968582;
			
			// aapt resource value: 0x7f04000e
			public const int layout01 = 2130968590;
			
			// aapt resource value: 0x7f040002
			public const int leftToRight = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int rightToLeft = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int textView1 = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int textView2 = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int textView3 = 2130968588;
			
			// aapt resource value: 0x7f040003
			public const int topToBottom = 2130968579;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int pen_content = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int close = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int open = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int option1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int option2 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int option3 = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MultiDirectionSlidingDrawer = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 5
			public const int MultiDirectionSlidingDrawer_allowSingleTap = 5;
			
			// aapt resource value: 6
			public const int MultiDirectionSlidingDrawer_animateOnClick = 6;
			
			// aapt resource value: 3
			public const int MultiDirectionSlidingDrawer_bottomOffset = 3;
			
			// aapt resource value: 2
			public const int MultiDirectionSlidingDrawer_content = 2;
			
			// aapt resource value: 0
			public const int MultiDirectionSlidingDrawer_direction = 0;
			
			// aapt resource value: 1
			public const int MultiDirectionSlidingDrawer_handle = 1;
			
			// aapt resource value: 4
			public const int MultiDirectionSlidingDrawer_topOffset = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
