#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LibrarySlideDateTimePicker.Resource", IsApplication=false)]

namespace LibrarySlideDateTimePicker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int gray_holo_dark = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int gray_holo_light = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int selection_divider = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public static int btnCancel = 2131165190;
			
			// aapt resource value: 0x7f070008
			public static int btnOk = 2131165192;
			
			// aapt resource value: 0x7f070005
			public static int buttonHorizontalDivider = 2131165189;
			
			// aapt resource value: 0x7f070007
			public static int buttonVerticalDivider = 2131165191;
			
			// aapt resource value: 0x7f070001
			public static int datePicker = 2131165185;
			
			// aapt resource value: 0x7f070003
			public static int slidingTabLayout = 2131165187;
			
			// aapt resource value: 0x7f070002
			public static int timePicker = 2131165186;
			
			// aapt resource value: 0x7f070000
			public static int txtTab = 2131165184;
			
			// aapt resource value: 0x7f070004
			public static int viewPager = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int CustomTabLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int FragmentDateLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int FragmentTimeLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int SlideDateTimePickerLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public static int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public static int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int AppTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
