#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SmoothProgressBar.Resource", IsApplication=true)]

namespace SmoothProgressBar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int pocket_interpolator = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0c0000
			public const int colors = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int gplus_colors = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int interpolators = 2131492866;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int spbStyle = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int spb_background = 2130771981;
			
			// aapt resource value: 0x7f010001
			public const int spb_color = 2130771969;
			
			// aapt resource value: 0x7f01000b
			public const int spb_colors = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int spb_generate_background_with_colors = 2130771982;
			
			// aapt resource value: 0x7f010008
			public const int spb_interpolator = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int spb_mirror_mode = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public const int spb_progressiveStart_activated = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int spb_progressiveStart_speed = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int spb_progressiveStop_speed = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int spb_reversed = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int spb_sections_count = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int spb_speed = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int spb_stroke_separator_length = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int spb_stroke_width = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f050000
			public const int spb_default_mirror_mode = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int spb_default_progressiveStart_activated = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int spb_default_reversed = 2131034114;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int gplus_color_1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int gplus_color_2 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int gplus_color_3 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int gplus_color_4 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int holo_blue_dark = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int holo_green_dark = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int holo_purple_dark = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int holo_red_dark = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int holo_yellow_dark = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int spb_default_color = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int spb_default_stroke_separator_length = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int spb_default_stroke_width = 2131230721;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070015
			public const int button_make = 2131165205;
			
			// aapt resource value: 0x7f070012
			public const int button_start = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int button_stop = 2131165203;
			
			// aapt resource value: 0x7f070006
			public const int checkbox_mirror = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int checkbox_reversed = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int container = 2131165204;
			
			// aapt resource value: 0x7f070019
			public const int progressBarAccelerateDecelerateInterpolator = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int progressBarAccelerateInterpolator = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int progressBarDecelerateInterpolator = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int progressBarLinearInterpolator = 2131165206;
			
			// aapt resource value: 0x7f070004
			public const int progressbar = 2131165188;
			
			// aapt resource value: 0x7f070010
			public const int seekbar_factor = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int seekbar_sections_count = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int seekbar_separator_length = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int seekbar_speed = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int seekbar_stroke_width = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int spb_interpolator_accelerate = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int spb_interpolator_acceleratedecelerate = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int spb_interpolator_decelerate = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int spb_interpolator_linear = 2131165185;
			
			// aapt resource value: 0x7f070011
			public const int spinner_interpolator = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int textview_factor = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int textview_sections_count = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int textview_separator_length = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int textview_speed = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int textview_stroke_width = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int spb_default_interpolator = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int spb_default_sections_count = 2131296257;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_custom = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a0002
			public const int app_name = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int hello = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int spb_default_speed = 2131361792;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b0002
			public const int AppTheme = 2131427330;
			
			// aapt resource value: 0x7f0b0005
			public const int GNowProgressBar = 2131427333;
			
			// aapt resource value: 0x7f0b0004
			public const int GPlusProgressBar = 2131427332;
			
			// aapt resource value: 0x7f0b0006
			public const int Mono_Android_Theme_Splash = 2131427334;
			
			// aapt resource value: 0x7f0b0003
			public const int ProgressBar_Horizontal = 2131427331;
			
			// aapt resource value: 0x7f0b0000
			public const int SmoothProgressBar = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int Theme_SmoothProgressBarDefaults = 2131427329;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SmoothProgressBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 0
			public const int SmoothProgressBar_spbStyle = 0;
			
			// aapt resource value: 13
			public const int SmoothProgressBar_spb_background = 13;
			
			// aapt resource value: 1
			public const int SmoothProgressBar_spb_color = 1;
			
			// aapt resource value: 11
			public const int SmoothProgressBar_spb_colors = 11;
			
			// aapt resource value: 14
			public const int SmoothProgressBar_spb_generate_background_with_colors = 14;
			
			// aapt resource value: 8
			public const int SmoothProgressBar_spb_interpolator = 8;
			
			// aapt resource value: 10
			public const int SmoothProgressBar_spb_mirror_mode = 10;
			
			// aapt resource value: 12
			public const int SmoothProgressBar_spb_progressiveStart_activated = 12;
			
			// aapt resource value: 6
			public const int SmoothProgressBar_spb_progressiveStart_speed = 6;
			
			// aapt resource value: 7
			public const int SmoothProgressBar_spb_progressiveStop_speed = 7;
			
			// aapt resource value: 9
			public const int SmoothProgressBar_spb_reversed = 9;
			
			// aapt resource value: 4
			public const int SmoothProgressBar_spb_sections_count = 4;
			
			// aapt resource value: 5
			public const int SmoothProgressBar_spb_speed = 5;
			
			// aapt resource value: 3
			public const int SmoothProgressBar_spb_stroke_separator_length = 3;
			
			// aapt resource value: 2
			public const int SmoothProgressBar_spb_stroke_width = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
