#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LibraryPullZoomView.Resource", IsApplication=false)]

namespace LibraryPullZoomView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public static int contentView = 2130771974;
			
			// aapt resource value: 0x7f010005
			public static int headerView = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int isHeadParallax = 2130771972;
			
			// aapt resource value: 0x7f010008
			public static int isHeaderParallax = 2130771976;
			
			// aapt resource value: 0x7f010003
			public static int listHeadView = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int scrollContentView = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int scrollHeadView = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int scrollZoomView = 2130771970;
			
			// aapt resource value: 0x7f010007
			public static int zoomView = 2130771975;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f020000
			public static int scrollview = 2130837504;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public static int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToZoomListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public static int PullToZoomListView_isHeadParallax = 1;
			
			// aapt resource value: 0
			public static int PullToZoomListView_listHeadView = 0;
			
			public static int[] PullToZoomScrollView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public static int PullToZoomScrollView_scrollContentView = 1;
			
			// aapt resource value: 0
			public static int PullToZoomScrollView_scrollHeadView = 0;
			
			// aapt resource value: 2
			public static int PullToZoomScrollView_scrollZoomView = 2;
			
			public static int[] PullToZoomView = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public static int PullToZoomView_contentView = 1;
			
			// aapt resource value: 0
			public static int PullToZoomView_headerView = 0;
			
			// aapt resource value: 3
			public static int PullToZoomView_isHeaderParallax = 3;
			
			// aapt resource value: 2
			public static int PullToZoomView_zoomView = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
