#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GoogleProgressBar.Resource", IsApplication=true)]

namespace GoogleProgressBar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LibraryGoogleProgressBar.Resource.Array.google_colors = global::GoogleProgressBar.Resource.Array.google_colors;
			global::LibraryGoogleProgressBar.Resource.Color.blue = global::GoogleProgressBar.Resource.Color.blue;
			global::LibraryGoogleProgressBar.Resource.Color.green = global::GoogleProgressBar.Resource.Color.green;
			global::LibraryGoogleProgressBar.Resource.Color.red = global::GoogleProgressBar.Resource.Color.red;
			global::LibraryGoogleProgressBar.Resource.Color.yellow = global::GoogleProgressBar.Resource.Color.yellow;
			global::LibraryGoogleProgressBar.Resource.Integer.default_type = global::GoogleProgressBar.Resource.Integer.default_type;
			global::LibraryGoogleProgressBar.Resource.String.library_name = global::GoogleProgressBar.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050002
			public const int default_color_choice_values = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int google_colors = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int progressDrawablesValues = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int cal_choices = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int cal_itemLayout = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int cal_numColumns = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int isTablet = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int blue = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int darkblue = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int darkgreen = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int darkorange = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int darkpurple = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int green = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int red = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int yellow = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080004
			public const int activity_horizontal_margin = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int activity_vertical_margin = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int color_swatch_large = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int color_swatch_margins_large = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int color_swatch_margins_small = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int color_swatch_small = 2131230721;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0001
			public const int google_progress = 2131427329;
			
			// aapt resource value: 0x7f0b0000
			public const int parentView = 2131427328;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int default_type = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070006
			public const int action_settings = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int app_name = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int color_picker_default_title = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int color_swatch_description = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int color_swatch_description_selected = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int firstcolor_pref_key = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int fourthcolor_pref_key = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int hello = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int library_name = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int pref_colors_header_title = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int progressBar_pref_defValue = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int progressBar_pref_key = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int secondcolor_pref_key = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int thirdcolor_pref_key = 2131165196;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int Mono_Android_Theme_Splash = 2131361792;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorPickerPreference = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int ColorPickerPreference_cal_choices = 1;
			
			// aapt resource value: 0
			public const int ColorPickerPreference_cal_itemLayout = 0;
			
			// aapt resource value: 2
			public const int ColorPickerPreference_cal_numColumns = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
