#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SamplePopover.Resource", IsApplication=true)]

namespace SamplePopover
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PopOver.Resource.Drawable.background_popover = global::SamplePopover.Resource.Drawable.background_popover;
			global::PopOver.Resource.Drawable.ic_launcher = global::SamplePopover.Resource.Drawable.ic_launcher;
			global::PopOver.Resource.Drawable.Icon = global::SamplePopover.Resource.Drawable.Icon;
			global::PopOver.Resource.Drawable.icon_popover_arrow_down = global::SamplePopover.Resource.Drawable.icon_popover_arrow_down;
			global::PopOver.Resource.Drawable.icon_popover_arrow_left = global::SamplePopover.Resource.Drawable.icon_popover_arrow_left;
			global::PopOver.Resource.Drawable.icon_popover_arrow_right = global::SamplePopover.Resource.Drawable.icon_popover_arrow_right;
			global::PopOver.Resource.Drawable.icon_popover_arrow_up = global::SamplePopover.Resource.Drawable.icon_popover_arrow_up;
			global::PopOver.Resource.String.library_name = global::SamplePopover.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_popover = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_popover_arrow_down = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_popover_arrow_left = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_popover_arrow_right = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_popover_arrow_up = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int btnTest = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int button1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int button2 = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int button4 = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int button5 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int button6 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int button7 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int button8 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int button9 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int mainScrollView = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int rootLayout = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int textView1 = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int popover_showed_view = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int lore_ipsum = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
