#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LibraryFloatLable.Resource", IsApplication=false)]

namespace LibraryFloatLable
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f030000
			public static int weddingparty_floatlabel_slide_from_bottom = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int weddingparty_floatlabel_slide_to_bottom = 2130903041;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int fitScreenWidth = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int gravity = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int hint = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int inputType = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int text = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int textColorHintFocused = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int textColorHintUnFocused = 2130771975;
			
			// aapt resource value: 0x7f010005
			public static int textSize = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public static int holo_blue_dark = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040004
			public static int center = 2130968580;
			
			// aapt resource value: 0x7f040008
			public static int floating_label_edit_text = 2130968584;
			
			// aapt resource value: 0x7f040007
			public static int floating_label_hint = 2130968583;
			
			// aapt resource value: 0x7f040000
			public static int full = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int half = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int left = 2130968578;
			
			// aapt resource value: 0x7f040005
			public static int normal = 2130968581;
			
			// aapt resource value: 0x7f040003
			public static int right = 2130968579;
			
			// aapt resource value: 0x7f040006
			public static int textPassword = 2130968582;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int FloatLabelEditText = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public static int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatLabelEditText = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public static int FloatLabelEditText_fitScreenWidth = 0;
			
			// aapt resource value: 1
			public static int FloatLabelEditText_gravity = 1;
			
			// aapt resource value: 2
			public static int FloatLabelEditText_hint = 2;
			
			// aapt resource value: 3
			public static int FloatLabelEditText_inputType = 3;
			
			// aapt resource value: 4
			public static int FloatLabelEditText_text = 4;
			
			// aapt resource value: 6
			public static int FloatLabelEditText_textColorHintFocused = 6;
			
			// aapt resource value: 7
			public static int FloatLabelEditText_textColorHintUnFocused = 7;
			
			// aapt resource value: 5
			public static int FloatLabelEditText_textSize = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
