#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LibraryHoloCircularProgressBar.Resource", IsApplication=false)]

namespace LibraryHoloCircularProgressBar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public static int circularProgressBarStyle = 2130771975;
			
			// aapt resource value: 0x7f010002
			public static int marker_progress = 2130771970;
			
			// aapt resource value: 0x7f010006
			public static int marker_visible = 2130771974;
			
			// aapt resource value: 0x7f010001
			public static int progress = 2130771969;
			
			// aapt resource value: 0x7f010004
			public static int progress_background_color = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int progress_color = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int stroke_width = 2130771968;
			
			// aapt resource value: 0x7f010005
			public static int thumb_visible = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f030000
			public static int CircularProgressBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int CircularProgressBarLight = 2130903041;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] HoloCircularProgressBar = new int[] {
					16842927,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public static int HoloCircularProgressBar_android_gravity = 0;
			
			// aapt resource value: 3
			public static int HoloCircularProgressBar_marker_progress = 3;
			
			// aapt resource value: 7
			public static int HoloCircularProgressBar_marker_visible = 7;
			
			// aapt resource value: 2
			public static int HoloCircularProgressBar_progress = 2;
			
			// aapt resource value: 5
			public static int HoloCircularProgressBar_progress_background_color = 5;
			
			// aapt resource value: 4
			public static int HoloCircularProgressBar_progress_color = 4;
			
			// aapt resource value: 1
			public static int HoloCircularProgressBar_stroke_width = 1;
			
			// aapt resource value: 6
			public static int HoloCircularProgressBar_thumb_visible = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
