#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ColorPickerViewDemo.Resource", IsApplication=true)]

namespace ColorPickerViewDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ColorPicker.Resource.Attribute.alphaChannelText = global::ColorPickerViewDemo.Resource.Attribute.alphaChannelText;
			global::ColorPicker.Resource.Attribute.alphaChannelVisible = global::ColorPickerViewDemo.Resource.Attribute.alphaChannelVisible;
			global::ColorPicker.Resource.Attribute.colorPickerBorderColor = global::ColorPickerViewDemo.Resource.Attribute.colorPickerBorderColor;
			global::ColorPicker.Resource.Attribute.colorPickerSliderColor = global::ColorPickerViewDemo.Resource.Attribute.colorPickerSliderColor;
			global::ColorPicker.Resource.Attribute.showDialogTitle = global::ColorPickerViewDemo.Resource.Attribute.showDialogTitle;
			global::ColorPicker.Resource.Attribute.showSelectedColorInList = global::ColorPickerViewDemo.Resource.Attribute.showSelectedColorInList;
			global::ColorPicker.Resource.Color.aqua = global::ColorPickerViewDemo.Resource.Color.aqua;
			global::ColorPicker.Resource.Color.black = global::ColorPickerViewDemo.Resource.Color.black;
			global::ColorPicker.Resource.Color.blue = global::ColorPickerViewDemo.Resource.Color.blue;
			global::ColorPicker.Resource.Color.def = global::ColorPickerViewDemo.Resource.Color.def;
			global::ColorPicker.Resource.Color.fuchsia = global::ColorPickerViewDemo.Resource.Color.fuchsia;
			global::ColorPicker.Resource.Color.gray = global::ColorPickerViewDemo.Resource.Color.gray;
			global::ColorPicker.Resource.Color.green = global::ColorPickerViewDemo.Resource.Color.green;
			global::ColorPicker.Resource.Color.lime = global::ColorPickerViewDemo.Resource.Color.lime;
			global::ColorPicker.Resource.Color.maroon = global::ColorPickerViewDemo.Resource.Color.maroon;
			global::ColorPicker.Resource.Color.navy = global::ColorPickerViewDemo.Resource.Color.navy;
			global::ColorPicker.Resource.Color.olive = global::ColorPickerViewDemo.Resource.Color.olive;
			global::ColorPicker.Resource.Color.purple = global::ColorPickerViewDemo.Resource.Color.purple;
			global::ColorPicker.Resource.Color.red = global::ColorPickerViewDemo.Resource.Color.red;
			global::ColorPicker.Resource.Color.silver = global::ColorPickerViewDemo.Resource.Color.silver;
			global::ColorPicker.Resource.Color.teal = global::ColorPickerViewDemo.Resource.Color.teal;
			global::ColorPicker.Resource.Color.white = global::ColorPickerViewDemo.Resource.Color.white;
			global::ColorPicker.Resource.Color.yellow = global::ColorPickerViewDemo.Resource.Color.yellow;
			global::ColorPicker.Resource.Id.color_panel_new = global::ColorPickerViewDemo.Resource.Id.color_panel_new;
			global::ColorPicker.Resource.Id.color_panel_old = global::ColorPickerViewDemo.Resource.Id.color_panel_old;
			global::ColorPicker.Resource.Id.color_picker_view = global::ColorPickerViewDemo.Resource.Id.color_picker_view;
			global::ColorPicker.Resource.Id.dialog_color_picker_extra_layout_landscape = global::ColorPickerViewDemo.Resource.Id.dialog_color_picker_extra_layout_landscape;
			global::ColorPicker.Resource.Id.preference_preview_color_panel = global::ColorPickerViewDemo.Resource.Id.preference_preview_color_panel;
			global::ColorPicker.Resource.Layout.dialog_color_picker = global::ColorPickerViewDemo.Resource.Layout.dialog_color_picker;
			global::ColorPicker.Resource.Layout.preference_preview_layout = global::ColorPickerViewDemo.Resource.Layout.preference_preview_layout;
			global::ColorPicker.Resource.String.dialog_cancle = global::ColorPickerViewDemo.Resource.String.dialog_cancle;
			global::ColorPicker.Resource.String.dialog_ok = global::ColorPickerViewDemo.Resource.String.dialog_ok;
			global::ColorPicker.Resource.String.dialog_title = global::ColorPickerViewDemo.Resource.String.dialog_title;
			global::ColorPicker.Resource.String.library_name = global::ColorPickerViewDemo.Resource.String.library_name;
			global::ColorPicker.Resource.Style.dialog_color_pciker_view_portrait = global::ColorPickerViewDemo.Resource.Style.dialog_color_pciker_view_portrait;
			global::ColorPicker.Resource.Styleable.ColorPickerPreference = global::ColorPickerViewDemo.Resource.Styleable.ColorPickerPreference;
			global::ColorPicker.Resource.Styleable.ColorPickerPreference_showDialogTitle = global::ColorPickerViewDemo.Resource.Styleable.ColorPickerPreference_showDialogTitle;
			global::ColorPicker.Resource.Styleable.ColorPickerPreference_showSelectedColorInList = global::ColorPickerViewDemo.Resource.Styleable.ColorPickerPreference_showSelectedColorInList;
			global::ColorPicker.Resource.Styleable.ColorPickerView = global::ColorPickerViewDemo.Resource.Styleable.ColorPickerView;
			global::ColorPicker.Resource.Styleable.ColorPickerView_alphaChannelText = global::ColorPickerViewDemo.Resource.Styleable.ColorPickerView_alphaChannelText;
			global::ColorPicker.Resource.Styleable.ColorPickerView_alphaChannelVisible = global::ColorPickerViewDemo.Resource.Styleable.ColorPickerView_alphaChannelVisible;
			global::ColorPicker.Resource.Styleable.ColorPickerView_colorPickerBorderColor = global::ColorPickerViewDemo.Resource.Styleable.ColorPickerView_colorPickerBorderColor;
			global::ColorPicker.Resource.Styleable.ColorPickerView_colorPickerSliderColor = global::ColorPickerViewDemo.Resource.Styleable.ColorPickerView_colorPickerSliderColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int alphaChannelText = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int alphaChannelVisible = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int colorPickerBorderColor = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int colorPickerSliderColor = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int showDialogTitle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int showSelectedColorInList = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int aqua = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public const int black = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int blue = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int def = 2130968592;
			
			// aapt resource value: 0x7f040002
			public const int fuchsia = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int gray = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int green = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int lime = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int maroon = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int navy = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int olive = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int purple = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int red = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int silver = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int teal = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int yellow = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_color_palette = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int buttonbar = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int cancelButton = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int color_panel_new = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int color_panel_old = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int color_picker_view = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int dialog_color_picker_extra_layout_landscape = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int menu_about = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int menu_color_picker_dialog = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int okButton = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int preference_preview_color_panel = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_color_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_about = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_color_picker = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int preference_preview_layout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060005
			public const int action_settings = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int app_name = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int dialog_cancle = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int dialog_ok = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int dialog_title = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int hello_world = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int AppBaseTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int AppTheme = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int dialog_color_pciker_view_portrait = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorPickerPreference = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int ColorPickerPreference_showDialogTitle = 0;
			
			// aapt resource value: 1
			public const int ColorPickerPreference_showSelectedColorInList = 1;
			
			public static int[] ColorPickerView = new int[]
			{
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public const int ColorPickerView_alphaChannelText = 1;
			
			// aapt resource value: 0
			public const int ColorPickerView_alphaChannelVisible = 0;
			
			// aapt resource value: 3
			public const int ColorPickerView_colorPickerBorderColor = 3;
			
			// aapt resource value: 2
			public const int ColorPickerView_colorPickerSliderColor = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
