#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SlideDateTimePicker.Resource", IsApplication=true)]

namespace SlideDateTimePicker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LibrarySlideDateTimePicker.Resource.Color.gray_holo_dark = global::SlideDateTimePicker.Resource.Color.gray_holo_dark;
			global::LibrarySlideDateTimePicker.Resource.Color.gray_holo_light = global::SlideDateTimePicker.Resource.Color.gray_holo_light;
			global::LibrarySlideDateTimePicker.Resource.Drawable.selection_divider = global::SlideDateTimePicker.Resource.Drawable.selection_divider;
			global::LibrarySlideDateTimePicker.Resource.Id.btnCancel = global::SlideDateTimePicker.Resource.Id.btnCancel;
			global::LibrarySlideDateTimePicker.Resource.Id.btnOk = global::SlideDateTimePicker.Resource.Id.btnOk;
			global::LibrarySlideDateTimePicker.Resource.Id.buttonHorizontalDivider = global::SlideDateTimePicker.Resource.Id.buttonHorizontalDivider;
			global::LibrarySlideDateTimePicker.Resource.Id.buttonVerticalDivider = global::SlideDateTimePicker.Resource.Id.buttonVerticalDivider;
			global::LibrarySlideDateTimePicker.Resource.Id.datePicker = global::SlideDateTimePicker.Resource.Id.datePicker;
			global::LibrarySlideDateTimePicker.Resource.Id.slidingTabLayout = global::SlideDateTimePicker.Resource.Id.slidingTabLayout;
			global::LibrarySlideDateTimePicker.Resource.Id.timePicker = global::SlideDateTimePicker.Resource.Id.timePicker;
			global::LibrarySlideDateTimePicker.Resource.Id.txtTab = global::SlideDateTimePicker.Resource.Id.txtTab;
			global::LibrarySlideDateTimePicker.Resource.Id.viewPager = global::SlideDateTimePicker.Resource.Id.viewPager;
			global::LibrarySlideDateTimePicker.Resource.Layout.CustomTabLayout = global::SlideDateTimePicker.Resource.Layout.CustomTabLayout;
			global::LibrarySlideDateTimePicker.Resource.Layout.FragmentDateLayout = global::SlideDateTimePicker.Resource.Layout.FragmentDateLayout;
			global::LibrarySlideDateTimePicker.Resource.Layout.FragmentTimeLayout = global::SlideDateTimePicker.Resource.Layout.FragmentTimeLayout;
			global::LibrarySlideDateTimePicker.Resource.Layout.SlideDateTimePickerLayout = global::SlideDateTimePicker.Resource.Layout.SlideDateTimePickerLayout;
			global::LibrarySlideDateTimePicker.Resource.String.library_name = global::SlideDateTimePicker.Resource.String.library_name;
			global::LibrarySlideDateTimePicker.Resource.Style.AppBaseTheme = global::SlideDateTimePicker.Resource.Style.AppBaseTheme;
			global::LibrarySlideDateTimePicker.Resource.Style.AppTheme = global::SlideDateTimePicker.Resource.Style.AppTheme;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int gray_holo_dark = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int gray_holo_light = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int selection_divider = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int btnCancel = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int btnClick = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int btnOk = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int buttonHorizontalDivider = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int buttonVerticalDivider = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int datePicker = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int slidingTabLayout = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int timePicker = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int txtTab = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int viewPager = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomTabLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FragmentDateLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentTimeLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SlideDateTimePickerLayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Mono_Android_Theme_Splash = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
