#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PullZoomView.Resource", IsApplication=true)]

namespace PullZoomView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LibraryPullZoomView.Resource.Attribute.contentView = global::PullZoomView.Resource.Attribute.contentView;
			global::LibraryPullZoomView.Resource.Attribute.headerView = global::PullZoomView.Resource.Attribute.headerView;
			global::LibraryPullZoomView.Resource.Attribute.isHeadParallax = global::PullZoomView.Resource.Attribute.isHeadParallax;
			global::LibraryPullZoomView.Resource.Attribute.isHeaderParallax = global::PullZoomView.Resource.Attribute.isHeaderParallax;
			global::LibraryPullZoomView.Resource.Attribute.listHeadView = global::PullZoomView.Resource.Attribute.listHeadView;
			global::LibraryPullZoomView.Resource.Attribute.scrollContentView = global::PullZoomView.Resource.Attribute.scrollContentView;
			global::LibraryPullZoomView.Resource.Attribute.scrollHeadView = global::PullZoomView.Resource.Attribute.scrollHeadView;
			global::LibraryPullZoomView.Resource.Attribute.scrollZoomView = global::PullZoomView.Resource.Attribute.scrollZoomView;
			global::LibraryPullZoomView.Resource.Attribute.zoomView = global::PullZoomView.Resource.Attribute.zoomView;
			global::LibraryPullZoomView.Resource.Id.scrollview = global::PullZoomView.Resource.Id.scrollview;
			global::LibraryPullZoomView.Resource.String.app_name = global::PullZoomView.Resource.String.app_name;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomListView = global::PullZoomView.Resource.Styleable.PullToZoomListView;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomListView_isHeadParallax = global::PullZoomView.Resource.Styleable.PullToZoomListView_isHeadParallax;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomListView_listHeadView = global::PullZoomView.Resource.Styleable.PullToZoomListView_listHeadView;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomScrollView = global::PullZoomView.Resource.Styleable.PullToZoomScrollView;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomScrollView_scrollContentView = global::PullZoomView.Resource.Styleable.PullToZoomScrollView_scrollContentView;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomScrollView_scrollHeadView = global::PullZoomView.Resource.Styleable.PullToZoomScrollView_scrollHeadView;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomScrollView_scrollZoomView = global::PullZoomView.Resource.Styleable.PullToZoomScrollView_scrollZoomView;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomView = global::PullZoomView.Resource.Styleable.PullToZoomView;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomView_contentView = global::PullZoomView.Resource.Styleable.PullToZoomView_contentView;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomView_headerView = global::PullZoomView.Resource.Styleable.PullToZoomView_headerView;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomView_isHeaderParallax = global::PullZoomView.Resource.Styleable.PullToZoomView_isHeaderParallax;
			global::LibraryPullZoomView.Resource.Styleable.PullToZoomView_zoomView = global::PullZoomView.Resource.Styleable.PullToZoomView_zoomView;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int contentView = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int headerView = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int isHeadParallax = 2130771972;
			
			// aapt resource value: 0x7f010008
			public const int isHeaderParallax = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int listHeadView = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int scrollContentView = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int scrollHeadView = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int scrollZoomView = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int zoomView = 2130771975;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_img_line_v = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_img_profile_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_img_user_default = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monoandroidsplash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int splash01 = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040013
			public const int action_disable_zoom = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int action_enable_zoom = 2130968596;
			
			// aapt resource value: 0x7f040011
			public const int action_hide_head = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int action_normal = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int action_parallax = 2130968592;
			
			// aapt resource value: 0x7f040015
			public const int action_settings = 2130968597;
			
			// aapt resource value: 0x7f040012
			public const int action_show_head = 2130968594;
			
			// aapt resource value: 0x7f040001
			public const int btnList = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int btnScroll = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int iv_user_head = 2130968583;
			
			// aapt resource value: 0x7f04000c
			public const int iv_zoom = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int layout_view = 2130968582;
			
			// aapt resource value: 0x7f04000d
			public const int listView = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int ll_action_button = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int scrollView = 2130968590;
			
			// aapt resource value: 0x7f040000
			public const int scrollview = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int tv_login = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int tv_register = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int tv_test1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int tv_test2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int tv_test3 = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int tv_user_name = 2130968584;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_head_zoom_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int profile_content_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int profile_head_view = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int profile_zoom_view = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PullToZoomListViewLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PullToZoomScrollViewLayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int list_view = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int main = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int scroll_view = 2131230722;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050009
			public const int action_disable_zoom = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int action_enable_zoom = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int action_hide_head = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int action_normal = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int action_parallax = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int action_settings = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int action_show_head = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int hello_world = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int title_pull_to_zoom_list_view = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int title_pull_to_zoom_scroll_view = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToZoomListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int PullToZoomListView_isHeadParallax = 1;
			
			// aapt resource value: 0
			public const int PullToZoomListView_listHeadView = 0;
			
			public static int[] PullToZoomScrollView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int PullToZoomScrollView_scrollContentView = 1;
			
			// aapt resource value: 0
			public const int PullToZoomScrollView_scrollHeadView = 0;
			
			// aapt resource value: 2
			public const int PullToZoomScrollView_scrollZoomView = 2;
			
			public static int[] PullToZoomView = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int PullToZoomView_contentView = 1;
			
			// aapt resource value: 0
			public const int PullToZoomView_headerView = 0;
			
			// aapt resource value: 3
			public const int PullToZoomView_isHeaderParallax = 3;
			
			// aapt resource value: 2
			public const int PullToZoomView_zoomView = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
