#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HoloCircularProgressBar.Resource", IsApplication=true)]

namespace HoloCircularProgressBar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LibraryHoloCircularProgressBar.Resource.Attribute.circularProgressBarStyle = global::HoloCircularProgressBar.Resource.Attribute.circularProgressBarStyle;
			global::LibraryHoloCircularProgressBar.Resource.Attribute.marker_progress = global::HoloCircularProgressBar.Resource.Attribute.marker_progress;
			global::LibraryHoloCircularProgressBar.Resource.Attribute.marker_visible = global::HoloCircularProgressBar.Resource.Attribute.marker_visible;
			global::LibraryHoloCircularProgressBar.Resource.Attribute.progress = global::HoloCircularProgressBar.Resource.Attribute.progress;
			global::LibraryHoloCircularProgressBar.Resource.Attribute.progress_background_color = global::HoloCircularProgressBar.Resource.Attribute.progress_background_color;
			global::LibraryHoloCircularProgressBar.Resource.Attribute.progress_color = global::HoloCircularProgressBar.Resource.Attribute.progress_color;
			global::LibraryHoloCircularProgressBar.Resource.Attribute.stroke_width = global::HoloCircularProgressBar.Resource.Attribute.stroke_width;
			global::LibraryHoloCircularProgressBar.Resource.Attribute.thumb_visible = global::HoloCircularProgressBar.Resource.Attribute.thumb_visible;
			global::LibraryHoloCircularProgressBar.Resource.String.library_name = global::HoloCircularProgressBar.Resource.String.library_name;
			global::LibraryHoloCircularProgressBar.Resource.Style.CircularProgressBar = global::HoloCircularProgressBar.Resource.Style.CircularProgressBar;
			global::LibraryHoloCircularProgressBar.Resource.Style.CircularProgressBarLight = global::HoloCircularProgressBar.Resource.Style.CircularProgressBarLight;
			global::LibraryHoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar = global::HoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar;
			global::LibraryHoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_android_gravity = global::HoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_android_gravity;
			global::LibraryHoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_marker_progress = global::HoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_marker_progress;
			global::LibraryHoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_marker_visible = global::HoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_marker_visible;
			global::LibraryHoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_progress = global::HoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_progress;
			global::LibraryHoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_progress_background_color = global::HoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_progress_background_color;
			global::LibraryHoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_progress_color = global::HoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_progress_color;
			global::LibraryHoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_stroke_width = global::HoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_stroke_width;
			global::LibraryHoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_thumb_visible = global::HoloCircularProgressBar.Resource.Styleable.HoloCircularProgressBar_thumb_visible;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int circularProgressBarStyle = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int marker_progress = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int marker_visible = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int progress = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int progress_background_color = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int progress_color = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int stroke_width = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int thumb_visible = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int btnOne = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int btnRandomColor = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int btnZero = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int holoCircularProgressBar = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int menu_switch_theme = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int togAnimation = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int zero = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int circular_progress_bar_sample = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int action_settings = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int random_color = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int switch_theme = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050003
			public const int AppTheme = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int AppThemeLight = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int CircularProgressBar = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int CircularProgressBarLight = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Mono_Android_Theme_Splash = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] HoloCircularProgressBar = new int[] {
					16842927,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int HoloCircularProgressBar_android_gravity = 0;
			
			// aapt resource value: 3
			public const int HoloCircularProgressBar_marker_progress = 3;
			
			// aapt resource value: 7
			public const int HoloCircularProgressBar_marker_visible = 7;
			
			// aapt resource value: 2
			public const int HoloCircularProgressBar_progress = 2;
			
			// aapt resource value: 5
			public const int HoloCircularProgressBar_progress_background_color = 5;
			
			// aapt resource value: 4
			public const int HoloCircularProgressBar_progress_color = 4;
			
			// aapt resource value: 1
			public const int HoloCircularProgressBar_stroke_width = 1;
			
			// aapt resource value: 6
			public const int HoloCircularProgressBar_thumb_visible = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
