#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ColorPicker.Resource", IsApplication=false)]

namespace ColorPicker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int alphaChannelText = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int alphaChannelVisible = 2130771970;
			
			// aapt resource value: 0x7f010005
			public static int colorPickerBorderColor = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int colorPickerSliderColor = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int showDialogTitle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int showSelectedColorInList = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030009
			public static int aqua = 2130903049;
			
			// aapt resource value: 0x7f03000f
			public static int black = 2130903055;
			
			// aapt resource value: 0x7f03000d
			public static int blue = 2130903053;
			
			// aapt resource value: 0x7f030010
			public static int def = 2130903056;
			
			// aapt resource value: 0x7f030002
			public static int fuchsia = 2130903042;
			
			// aapt resource value: 0x7f030005
			public static int gray = 2130903045;
			
			// aapt resource value: 0x7f03000c
			public static int green = 2130903052;
			
			// aapt resource value: 0x7f03000a
			public static int lime = 2130903050;
			
			// aapt resource value: 0x7f030008
			public static int maroon = 2130903048;
			
			// aapt resource value: 0x7f03000e
			public static int navy = 2130903054;
			
			// aapt resource value: 0x7f030006
			public static int olive = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int purple = 2130903047;
			
			// aapt resource value: 0x7f030003
			public static int red = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int silver = 2130903044;
			
			// aapt resource value: 0x7f03000b
			public static int teal = 2130903051;
			
			// aapt resource value: 0x7f030000
			public static int white = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int yellow = 2130903041;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public static int color_panel_new = 2130968578;
			
			// aapt resource value: 0x7f040001
			public static int color_panel_old = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int color_picker_view = 2130968576;
			
			// aapt resource value: 0x7f040004
			public static int dialog_color_picker_extra_layout_landscape = 2130968580;
			
			// aapt resource value: 0x7f040003
			public static int preference_preview_color_panel = 2130968579;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int dialog_color_picker = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int preference_preview_layout = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public static int dialog_cancle = 2131034115;
			
			// aapt resource value: 0x7f050002
			public static int dialog_ok = 2131034114;
			
			// aapt resource value: 0x7f050001
			public static int dialog_title = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public static int dialog_color_pciker_view_portrait = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorPickerPreference = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public static int ColorPickerPreference_showDialogTitle = 0;
			
			// aapt resource value: 1
			public static int ColorPickerPreference_showSelectedColorInList = 1;
			
			public static int[] ColorPickerView = new int[]
			{
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public static int ColorPickerView_alphaChannelText = 1;
			
			// aapt resource value: 0
			public static int ColorPickerView_alphaChannelVisible = 0;
			
			// aapt resource value: 3
			public static int ColorPickerView_colorPickerBorderColor = 3;
			
			// aapt resource value: 2
			public static int ColorPickerView_colorPickerSliderColor = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
