#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ColorPicker.Resource", IsApplication=false)]

namespace ColorPicker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int alphaChannelText = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int alphaChannelVisible = 2130771970;
			
			// aapt resource value: 0x7f010005
			public static int colorPickerBorderColor = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int colorPickerSliderColor = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int showDialogTitle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int showSelectedColorInList = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030002
			public static int color_panel_new = 2130903042;
			
			// aapt resource value: 0x7f030001
			public static int color_panel_old = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int color_picker_view = 2130903040;
			
			// aapt resource value: 0x7f030004
			public static int dialog_color_picker_extra_layout_landscape = 2130903044;
			
			// aapt resource value: 0x7f030003
			public static int preference_preview_color_panel = 2130903043;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int dialog_color_picker = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int preference_preview_layout = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public static int dialog_cancle = 2130968579;
			
			// aapt resource value: 0x7f040002
			public static int dialog_ok = 2130968578;
			
			// aapt resource value: 0x7f040001
			public static int dialog_title = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public static int dialog_color_pciker_view_portrait = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorPickerPreference = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public static int ColorPickerPreference_showDialogTitle = 0;
			
			// aapt resource value: 1
			public static int ColorPickerPreference_showSelectedColorInList = 1;
			
			public static int[] ColorPickerView = new int[]
			{
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public static int ColorPickerView_alphaChannelText = 1;
			
			// aapt resource value: 0
			public static int ColorPickerView_alphaChannelVisible = 0;
			
			// aapt resource value: 3
			public static int ColorPickerView_colorPickerBorderColor = 3;
			
			// aapt resource value: 2
			public static int ColorPickerView_colorPickerSliderColor = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
