#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PopOver.Resource", IsApplication=false)]

namespace PopOver
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int background_popover = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int icon_popover_arrow_down = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int icon_popover_arrow_left = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int icon_popover_arrow_right = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int icon_popover_arrow_up = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public static int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
